name: Poll & Transform coronavirus-cases_latest.csv

on:
  push:
  schedule:
    - cron: "7,37 9-18 * * *"

jobs:
  poll_transform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Poll & Transform
      run: |
        cd src && python3 main.py && cd ..
    - name: Workflow Debug
      run: |
        pwd && ls -lah
    - name: Set variable to check if anything changed
      id: is_updated
      run: |-
        echo "##[set-output name=changed;]$(git diff --quiet HEAD data/*.csv; echo $?)"
    - name: Commit files
      if: steps.is_updated.outputs.changed != 0
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data
        git commit -m "Update for $(date +'%Y-%m-%d')"
    - name: Push changes
      if: steps.decide_variable.outputs.changed != 0
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
